sonar.projectKey=jxjidev_MAREA
sonar.organization=jxjidev

sonar.sources=backend/src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js

sonar.tests=backend/src
sonar.test.inclusions=**/*.test.js

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.sourceEncoding=UTF-8